navbar:
  blog_title: lengband
footer:
  statistics:
    enable: false
    source: "busuanzi"  # 可选 leancloud | busuanzi  根据自己需求选择
    pv_format: "总访问量 {} 次"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"
index:
  slogan:
    enable: true
    text: 这是一个无聊的技术网站
    api:
      enable: false
      url: "https://v1.hitokoto.cn/"
      method: "GET"
      headers: {}
      keys: ["hitokoto"]
post:
  comments:
    enable: true
    type: valine
valine:
  enable: true
  appId: xePt3uRX5aQKQqpgdD1AXTCL-gzGzoHsz
  appKey: 0PvefXKIH5t02cQjQTucTeJI 
  avatar: 'lengband'
  placeholder: 'Free talk ~!'
  comment_count: true # 评论数量显示
  serverURLs: # 博客启用自定义域名后，请在此填写（默认情况下会自动检测到，无需填写）